src/main/java/fr/epsi/b3/model/Capteur.java
package fr.epsi.b3.model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

public class Capteur {

    private String name;
    private String unite;
    private List<Valeur> valeurs = new ArrayList<>();

    public List<Valeur> getValeurs() {
        return valeurs;
    }

    public void setValeurs(List<Valeur> valeurs) {
        this.valeurs = valeurs;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUnite() {
        return unite;
    }

    public void setUnite(String unite) {
        this.unite = unite;
    }

    public Valeur getLastValeur(){
        return valeurs.get(valeurs.size()-1);
    }

    public Valeur getMinValue(){
        return Collections.min(this.valeurs, Comparator.comparing(v -> v.getValue()));
    }

    public Valeur getMaxValue(){
        return Collections.max(this.valeurs, Comparator.comparing(v -> v.getValue()));
    }

    public double getAvgValeur(){
        int tot = 0;
        for (Valeur v: this.valeurs
             ) {
            tot += v.getValue();
        }
        return Math.round(tot/this.valeurs.size());
    }

    public String getFullName(){
        if (name.equals("TEMP")){
            return "Température";
        }
        return "Humidité";
    }
}

src/main/java/fr/epsi/b3/model/Valeur.java
package fr.epsi.b3.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

public class Valeur{
    private double value;
    @JsonFormat(pattern = "dd/MM/yyyy HH:mm:ss", timezone = "Europe/Paris")
    private Date date_value;

    public double getValue() {
        return value;
    }

    public void setValue(double value) {
        this.value = value;
    }

    public Date getDate_value() {
        return date_value;
    }

    public void setDate_value(Date date_value) {
        this.date_value = date_value;
    }

    public String getFormatedIntDate() {
        DateFormat jour = new SimpleDateFormat("yyyy-MM-dd");
        String jourString = jour.format(this.date_value);
        DateFormat secs = new SimpleDateFormat("HH:mm:ss");
        String secsString = secs.format(this.date_value);
        return jourString + "T" + secsString;
    }


}

src/main/webapp/WEB-INF/views/accueil.jsp
<%@page pageEncoding="UTF-8" contentType="text/html" %>
<%@taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="<c:url value="/resources/fontawesome-5.13.0/css/all.css"/>">
    <link rel="stylesheet" href="<c:url value="/resources/css/bootstrap.min.css"/>">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="<c:url value="/resources/js/bootstrap.min.js"/>"></script>
    <link rel="stylesheet" type="text/css" href="<c:url value="/resources/css/style.css"/>">
    <title>Accueil</title>
</head>
<html>
<body onbeforeunload="document.location.reload(true)">
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="<c:url value="/"/>"><i class="fas fa-home"></i></a>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="<c:url value="/logout"/>"><i class="fas fa-sign-out-alt"></i></a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="row">
        <div class="col-md-12 text-center">
            <div class="welcome-texte">
                <h1>Bienvenue <c:out value="${utilisateur.user_name.toUpperCase()}"></c:out></h1>
            </div>
        </div>
        <c:forEach var="device" items="${utilisateur.devices}">
            <div class="col-sm-1"></div>
            <c:forEach items="${device.capteurs}" var="capteur">
                <div class="col-sm-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title text-center">
                                <c:out value="Capteur : ${capteur.name}"></c:out>
                            </h5>
                            <p class="card-text text-center value-capteur">
                                <c:out value="${capteur.lastValeur.value}${capteur.unite}"></c:out>
                            </p>
                            <div class="text-center">
                                <a href="<c:url value="/details/${device.adresse_mac}/${capteur.name}"/>"
                                   class="btn btn-primary">Détails</a>
                            </div>
                        </div>
                    </div>
                </div>
                <c:if test="${device.capteurs.indexOf(capteur) == 0}">
                    <div class="col-sm-2"></div>
                </c:if>
            </c:forEach>
            <div class="col-sm-1"></div>
        </c:forEach>
    </div>
</div>
</body>
</html>

src/main/webapp/WEB-INF/views/connection.jsp
<%@page pageEncoding="UTF-8" contentType="text/html"%>
<%@taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="<c:url value="/resources/css/bootstrap.min.css"/>">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="<c:url value="/resources/js/bootstrap.min.js"/>"></script>
  <link rel="stylesheet" type="text/css" href="<c:url value="/resources/css/style.css"/>">
  <title>Se connecter</title>
</head>
<body>
<div class="login-form">
  <form:form servletRelativeAction="/connection" modelAttribute="utilisateurConnectionDto" acceptCharset="utf-8">
    <h2 class="text-center">Se connecter</h2>
    <div class="form-group">
      <form:input type="text" class="form-control" placeholder="Username" path="user_name"/>
      <form:errors path="user_name"/>
    </div>
    <div class="form-group">
      <form:input type="password" class="form-control" placeholder="Password" path="password"/>
      <form:errors path="password"/>
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary btn-block">Connexion</button>
    </div>
    <form:errors path="*"/>
  </form:form>
</div>
</body>
</html>

src/main/webapp/WEB-INF/views/details.jsp
<%@page pageEncoding="UTF-8" contentType="text/html" %>
<%@taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="<c:url value="/resources/fontawesome-5.13.0/css/all.css"/>">
    <link rel="stylesheet" href="<c:url value="/resources/css/bootstrap.min.css"/>">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="<c:url value="/resources/js/bootstrap.min.js"/>"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.js"></script>
    <link rel="stylesheet" type="text/css" href="<c:url value="/resources/css/style.css"/>">
    <script type="text/javascript">
        window.onload = function () {

            var dps = [];
            var chart = new CanvasJS.Chart("chartContainer", {
                theme: "light2", // "light1", "dark1", "dark2"
                animationEnabled: true,
                title: {
                    text: "${capteur.fullName}"
                },
                axisX: {
                    valueFormatString: "DD/MM HH:mm:ss"
                },
                axisY: {
                    title: "${capteur.fullName}",
                    suffix: "${capteur.unite}"
                },
                data: [{
                    type: "line",
                    xValueType: "dateTime",
                    xValueFormatString: "DD/MM HH:mm:ss",
                    yValueFormatString: "#,##0 ${capteur.unite}",
                    dataPoints: dps
                }]
            });


            var xValue;
            var yValue;

            <c:forEach items="${capteur.valeurs}" var="valeur" varStatus="loop">
            xValue = Date.parse("${valeur.formatedIntDate}");
            yValue = parseFloat("${valeur.value}");
            dps.push({
                x: xValue,
                y: yValue
            });
            </c:forEach>
            chart.render();
            console.log(dps);

        }
    </script>
    <title>Accueil</title>
</head>
<html>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="<c:url value="/"/>"><i class="fas fa-home"></i></a>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="<c:url value="/logout"/>"><i class="fas fa-sign-out-alt"></i></a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="row">
        <div class="col-md-12 text-center">
            <div class="welcome-texte">
                <h1>Détail <c:out value="${capteur.name}"></c:out></h1>
            </div>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-10" id="chartContainer" style="height: 370px;"></div>
        <div class="col-md-1"></div>
    </div>
    <div class="separateur"></div>
    <div class="row">
        <div class="col-md-5">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Valeur</th>
                    <th scope="col">Date</th>
                </tr>
                </thead>
                <tbody>
                <c:forEach items="${capteur.valeurs}" var="valeur">
                    <tr>
                        <td><c:out value="${valeur.value} ${capteur.unite}"/></td>
                        <td><c:out value="${valeur.date_value}"/></td>
                    </tr>
                </c:forEach>
                </tbody>
            </table>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-4">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Valeur la plus haute</th>
                    <th scope="col">Valeur la plus basse</th>
                    <th scope="col">Moyenne</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><c:out value="${capteur.maxValue.value} ${capteur.unite}"/></td>
                    <td><c:out value="${capteur.minValue.value} ${capteur.unite}"/></td>
                    <td><c:out value="${capteur.avgValeur} ${capteur.unite}"/></td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>
</body>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
</html>